# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_paymenthistory_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fee.Section'),
        ),
    ]
